import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/layout/SideBar";
import Header from "@/components/layout/Header";
import ConditionalLayout from "@/components/layout/ConditionalLayout";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Personal Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex flex-col h-screen overflow-hidden'>
          <Header />
          <div className='flex flex-1 overflow-hidden'>
            <Sidebar />
            <ConditionalLayout>{children}</ConditionalLayout>
          </div>
        </div>
      </body>
    </html>
  );
}
